-- Run in Supabase SQL editor
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null check (role in ('super_admin', 'team_lead', 'team_member', 'project_member')),
  plan text not null default 'free' check (plan in ('free', 'freelancer', 'agency', 'agency_pro')),
  stripe_customer_id text,
  stripe_subscription_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.onboarding_tokens (
  id uuid primary key default gen_random_uuid(),
  token text not null unique,
  project_slug text not null,
  created_by uuid references auth.users(id) on delete set null,
  expires_at timestamptz,
  max_uses int not null default 1000,
  used_count int not null default 0,
  password_hash text,
  password_plain text,
  revoked boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.templates (
  id text primary key,
  title text not null,
  description text not null,
  icon text not null,
  badge text not null,
  structure jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_by uuid references auth.users(id) on delete set null,
  description text not null default '',
  status text not null check (status in ('active', 'inactive')),
  lead jsonb,
  members jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  created_by uuid references auth.users(id) on delete set null,
  template_id text not null references public.templates(id) on delete restrict,
  status text not null check (status in ('completed', 'overdue', 'waiting', 'ongoing', 'onhold')),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  avatar_src text not null default '',
  team_ids bigint[] not null default '{}',
  extra_members jsonb not null default '[]'::jsonb,
  submissions jsonb not null default '{}'::jsonb
);

create table if not exists public.project_notes (
  id uuid primary key default gen_random_uuid(),
  project_id bigint not null references public.projects(id) on delete cascade,
  project_slug text not null,
  author_id uuid references auth.users(id) on delete set null,
  author_name text not null,
  author_avatar text,
  author_email text,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.project_note_reactions (
  id uuid primary key default gen_random_uuid(),
  note_id uuid not null references public.project_notes(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  emoji text not null,
  created_at timestamptz not null default now(),
  unique (note_id, user_id, emoji)
);

create table if not exists public.project_note_mentions (
  id uuid primary key default gen_random_uuid(),
  note_id uuid not null references public.project_notes(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  mentioned_email text not null,
  created_at timestamptz not null default now()
);

alter table public.profiles enable row level security;
alter table public.onboarding_tokens enable row level security;
alter table public.templates enable row level security;
alter table public.teams enable row level security;
alter table public.projects enable row level security;
alter table public.project_notes enable row level security;
alter table public.project_note_reactions enable row level security;
alter table public.project_note_mentions enable row level security;

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can upsert own profile" on public.profiles;
create policy "Users can upsert own profile"
on public.profiles
for all
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Authenticated users can read onboarding tokens" on public.onboarding_tokens;
create policy "Authenticated users can read onboarding tokens"
on public.onboarding_tokens
for select
to authenticated
using (true);

drop policy if exists "Public read templates" on public.templates;
create policy "Public read templates"
on public.templates
for select
to anon, authenticated
using (true);

drop policy if exists "Public read teams" on public.teams;
drop policy if exists "Public read projects" on public.projects;

drop policy if exists "Team owners can read" on public.teams;
create policy "Team owners can read"
on public.teams
for select
to authenticated
using (created_by = auth.uid());

drop policy if exists "Team members can read" on public.teams;
create policy "Team members can read"
on public.teams
for select
to authenticated
using (
  (lead ->> 'email') ilike (auth.jwt() ->> 'email')
  or exists (
    select 1
    from jsonb_array_elements(members) as member
    where (member ->> 'email') ilike (auth.jwt() ->> 'email')
  )
);

drop policy if exists "Project owners can read" on public.projects;
create policy "Project owners can read"
on public.projects
for select
to authenticated
using (created_by = auth.uid());

drop policy if exists "Project members can read" on public.projects;
create policy "Project members can read"
on public.projects
for select
to authenticated
using (
  exists (
    select 1
    from public.teams as team
    where team.id = any (projects.team_ids)
      and (
        (team.lead ->> 'email') ilike (auth.jwt() ->> 'email')
        or exists (
          select 1
          from jsonb_array_elements(team.members) as member
          where (member ->> 'email') ilike (auth.jwt() ->> 'email')
        )
      )
  )
  or exists (
    select 1
    from jsonb_array_elements(projects.extra_members) as member
    where (member ->> 'email') ilike (auth.jwt() ->> 'email')
  )
);

drop policy if exists "Project members can read notes" on public.project_notes;
create policy "Project members can read notes"
on public.project_notes
for select
to authenticated
using (
  exists (
    select 1
    from public.projects
    where projects.id = project_notes.project_id
      and (
        projects.created_by = auth.uid()
        or exists (
          select 1
          from public.teams as team
          where team.id = any (projects.team_ids)
            and (
              (team.lead ->> 'email') ilike (auth.jwt() ->> 'email')
              or exists (
                select 1
                from jsonb_array_elements(team.members) as member
                where (member ->> 'email') ilike (auth.jwt() ->> 'email')
              )
            )
        )
        or exists (
          select 1
          from jsonb_array_elements(projects.extra_members) as member
          where (member ->> 'email') ilike (auth.jwt() ->> 'email')
        )
      )
  )
);

drop policy if exists "Project members can add notes" on public.project_notes;
create policy "Project members can add notes"
on public.project_notes
for insert
to authenticated
with check (
  auth.uid() = author_id
  and exists (
    select 1
    from public.projects
    where projects.id = project_notes.project_id
      and (
        projects.created_by = auth.uid()
        or exists (
          select 1
          from public.teams as team
          where team.id = any (projects.team_ids)
            and (
              (team.lead ->> 'email') ilike (auth.jwt() ->> 'email')
              or exists (
                select 1
                from jsonb_array_elements(team.members) as member
                where (member ->> 'email') ilike (auth.jwt() ->> 'email')
              )
            )
        )
        or exists (
          select 1
          from jsonb_array_elements(projects.extra_members) as member
          where (member ->> 'email') ilike (auth.jwt() ->> 'email')
        )
      )
  )
);

drop policy if exists "Project members can read note reactions" on public.project_note_reactions;
create policy "Project members can read note reactions"
on public.project_note_reactions
for select
to authenticated
using (
  exists (
    select 1
    from public.projects
    where projects.id = project_note_reactions.project_id
      and (
        projects.created_by = auth.uid()
        or exists (
          select 1
          from public.teams as team
          where team.id = any (projects.team_ids)
            and (
              (team.lead ->> 'email') ilike (auth.jwt() ->> 'email')
              or exists (
                select 1
                from jsonb_array_elements(team.members) as member
                where (member ->> 'email') ilike (auth.jwt() ->> 'email')
              )
            )
        )
        or exists (
          select 1
          from jsonb_array_elements(projects.extra_members) as member
          where (member ->> 'email') ilike (auth.jwt() ->> 'email')
        )
      )
  )
);

drop policy if exists "Project members can add reactions" on public.project_note_reactions;
create policy "Project members can add reactions"
on public.project_note_reactions
for insert
to authenticated
with check (
  auth.uid() = user_id
  and exists (
    select 1
    from public.projects
    where projects.id = project_note_reactions.project_id
      and (
        projects.created_by = auth.uid()
        or exists (
          select 1
          from public.teams as team
          where team.id = any (projects.team_ids)
            and (
              (team.lead ->> 'email') ilike (auth.jwt() ->> 'email')
              or exists (
                select 1
                from jsonb_array_elements(team.members) as member
                where (member ->> 'email') ilike (auth.jwt() ->> 'email')
              )
            )
        )
        or exists (
          select 1
          from jsonb_array_elements(projects.extra_members) as member
          where (member ->> 'email') ilike (auth.jwt() ->> 'email')
        )
      )
  )
);

drop policy if exists "Project members can remove reactions" on public.project_note_reactions;
create policy "Project members can remove reactions"
on public.project_note_reactions
for delete
to authenticated
using (auth.uid() = user_id);

drop policy if exists "Users can read their note mentions" on public.project_note_mentions;
create policy "Users can read their note mentions"
on public.project_note_mentions
for select
to authenticated
using (lower(mentioned_email) = lower(auth.jwt() ->> 'email'));

drop policy if exists "Project members can add note mentions" on public.project_note_mentions;
create policy "Project members can add note mentions"
on public.project_note_mentions
for insert
to authenticated
with check (
  exists (
    select 1
    from public.projects
    where projects.id = project_note_mentions.project_id
      and (
        projects.created_by = auth.uid()
        or exists (
          select 1
          from public.teams as team
          where team.id = any (projects.team_ids)
            and (
              (team.lead ->> 'email') ilike (auth.jwt() ->> 'email')
              or exists (
                select 1
                from jsonb_array_elements(team.members) as member
                where (member ->> 'email') ilike (auth.jwt() ->> 'email')
              )
            )
        )
        or exists (
          select 1
          from jsonb_array_elements(projects.extra_members) as member
          where (member ->> 'email') ilike (auth.jwt() ->> 'email')
        )
      )
  )
);

grant select on public.templates to anon, authenticated;
grant select on public.teams to authenticated;
grant select on public.projects to authenticated;
grant select, insert on public.project_notes to authenticated;
grant select, insert, delete on public.project_note_reactions to authenticated;
grant select, insert on public.project_note_mentions to authenticated;

revoke select on public.teams from anon;
revoke select on public.projects from anon;
revoke select on public.project_notes from anon;
revoke select on public.project_note_reactions from anon;
revoke select on public.project_note_mentions from anon;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role, plan)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'role', 'super_admin'),
    coalesce(new.raw_user_meta_data ->> 'plan', 'free')
  )
  on conflict (id) do update
    set full_name = excluded.full_name,
        role = excluded.role,
        plan = excluded.plan,
        updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create index if not exists idx_projects_template_id on public.projects (template_id);
create index if not exists idx_projects_status on public.projects (status);
create index if not exists idx_projects_created_at on public.projects (created_at desc);
create index if not exists idx_projects_created_by on public.projects (created_by);
create index if not exists idx_project_notes_project_id on public.project_notes (project_id);
create index if not exists idx_project_notes_created_at on public.project_notes (created_at desc);
create index if not exists idx_project_note_reactions_note_id on public.project_note_reactions (note_id);
create index if not exists idx_project_note_reactions_project_id on public.project_note_reactions (project_id);
create index if not exists idx_project_note_mentions_note_id on public.project_note_mentions (note_id);
create index if not exists idx_project_note_mentions_project_id on public.project_note_mentions (project_id);
create index if not exists idx_project_note_mentions_email on public.project_note_mentions (mentioned_email);
create index if not exists idx_teams_slug on public.teams (slug);
create index if not exists idx_teams_created_by on public.teams (created_by);

-- For already-created tables that used GENERATED ALWAYS:
alter table if exists public.teams alter column id set generated by default;
alter table if exists public.projects alter column id set generated by default;
alter table if exists public.teams add column if not exists created_by uuid references auth.users(id) on delete set null;
alter table if exists public.projects add column if not exists created_by uuid references auth.users(id) on delete set null;
alter table if exists public.teams drop column if exists template_id;
alter table if exists public.onboarding_tokens
  add column if not exists password_hash text,
  add column if not exists password_plain text;

create or replace function public.sync_identity_sequences()
returns void
language plpgsql
security definer
as $$
begin
  perform setval(
    pg_get_serial_sequence('public.teams', 'id'),
    coalesce((select max(id) from public.teams), 1),
    true
  );

  perform setval(
    pg_get_serial_sequence('public.projects', 'id'),
    coalesce((select max(id) from public.projects), 1),
    true
  );
end;
$$;
