-- Run in Supabase SQL editor
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null check (role in ('agency', 'freelancer', 'project_member', 'team_member')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.onboarding_tokens (
  id uuid primary key default gen_random_uuid(),
  token text not null unique,
  project_slug text not null,
  created_by uuid references auth.users(id) on delete set null,
  expires_at timestamptz,
  max_uses int not null default 1000,
  used_count int not null default 0,
  password_hash text,
  password_plain text,
  revoked boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.templates (
  id text primary key,
  title text not null,
  description text not null,
  icon text not null,
  badge text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.teams (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  created_by uuid references auth.users(id) on delete set null,
  description text not null default '',
  status text not null check (status in ('active', 'inactive')),
  lead jsonb,
  members jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  created_by uuid references auth.users(id) on delete set null,
  template_id text not null references public.templates(id) on delete restrict,
  status text not null check (status in ('completed', 'overdue', 'waiting', 'ongoing', 'onhold')),
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  avatar_src text not null default '',
  team_ids bigint[] not null default '{}',
  extra_members jsonb not null default '[]'::jsonb,
  submissions jsonb not null default '{}'::jsonb
);

alter table public.profiles enable row level security;
alter table public.onboarding_tokens enable row level security;
alter table public.templates enable row level security;
alter table public.teams enable row level security;
alter table public.projects enable row level security;

drop policy if exists "Users can view own profile" on public.profiles;
create policy "Users can view own profile"
on public.profiles
for select
to authenticated
using (auth.uid() = id);

drop policy if exists "Users can upsert own profile" on public.profiles;
create policy "Users can upsert own profile"
on public.profiles
for all
to authenticated
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Authenticated users can read onboarding tokens" on public.onboarding_tokens;
create policy "Authenticated users can read onboarding tokens"
on public.onboarding_tokens
for select
to authenticated
using (true);

drop policy if exists "Public read templates" on public.templates;
create policy "Public read templates"
on public.templates
for select
to anon, authenticated
using (true);

drop policy if exists "Public read teams" on public.teams;
drop policy if exists "Public read projects" on public.projects;

drop policy if exists "Team owners can read" on public.teams;
create policy "Team owners can read"
on public.teams
for select
to authenticated
using (created_by = auth.uid());

drop policy if exists "Team members can read" on public.teams;
create policy "Team members can read"
on public.teams
for select
to authenticated
using (
  (lead ->> 'email') ilike (auth.jwt() ->> 'email')
  or exists (
    select 1
    from jsonb_array_elements(members) as member
    where (member ->> 'email') ilike (auth.jwt() ->> 'email')
  )
);

drop policy if exists "Project owners can read" on public.projects;
create policy "Project owners can read"
on public.projects
for select
to authenticated
using (created_by = auth.uid());

drop policy if exists "Project members can read" on public.projects;
create policy "Project members can read"
on public.projects
for select
to authenticated
using (
  exists (
    select 1
    from public.teams as team
    where team.id = any (projects.team_ids)
      and (
        (team.lead ->> 'email') ilike (auth.jwt() ->> 'email')
        or exists (
          select 1
          from jsonb_array_elements(team.members) as member
          where (member ->> 'email') ilike (auth.jwt() ->> 'email')
        )
      )
  )
  or exists (
    select 1
    from jsonb_array_elements(projects.extra_members) as member
    where (member ->> 'email') ilike (auth.jwt() ->> 'email')
  )
);

grant select on public.templates to anon, authenticated;
grant select on public.teams to authenticated;
grant select on public.projects to authenticated;

revoke select on public.teams from anon;
revoke select on public.projects from anon;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', ''),
    coalesce(new.raw_user_meta_data ->> 'role', 'agency')
  )
  on conflict (id) do update
    set full_name = excluded.full_name,
        role = excluded.role,
        updated_at = now();

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create index if not exists idx_projects_template_id on public.projects (template_id);
create index if not exists idx_projects_status on public.projects (status);
create index if not exists idx_projects_created_at on public.projects (created_at desc);
create index if not exists idx_projects_created_by on public.projects (created_by);
create index if not exists idx_teams_slug on public.teams (slug);
create index if not exists idx_teams_created_by on public.teams (created_by);

-- For already-created tables that used GENERATED ALWAYS:
alter table if exists public.teams alter column id set generated by default;
alter table if exists public.projects alter column id set generated by default;
alter table if exists public.teams add column if not exists created_by uuid references auth.users(id) on delete set null;
alter table if exists public.projects add column if not exists created_by uuid references auth.users(id) on delete set null;
alter table if exists public.teams drop column if exists template_id;
alter table if exists public.onboarding_tokens
  add column if not exists password_hash text,
  add column if not exists password_plain text;

create or replace function public.sync_identity_sequences()
returns void
language plpgsql
security definer
as $$
begin
  perform setval(
    pg_get_serial_sequence('public.teams', 'id'),
    coalesce((select max(id) from public.teams), 1),
    true
  );

  perform setval(
    pg_get_serial_sequence('public.projects', 'id'),
    coalesce((select max(id) from public.projects), 1),
    true
  );
end;
$$;
